Find installed GTestConfig rather than using find_GTest from CMake
Servicerobotics-Ulm/SmartSoftComponentDeveloperAPIcpp pull request #3
Opened 2019-12-04 14:47 UTC by ccvca

GTest liefert inzwischen eine eigene CMake-Einbindung mit, damit wird die Legacy-Variante, die bei CMake mitgeliefert wird, nicht mehr benötigt. Mit der neuen Variante ist jetzt auch das Auffinden mittels CMAKE_PREFIX_PATH möglich.

2019-12-04 15:12 UTC, alex-lotz requested changes
Our policy is to keep GTests optional, which is broken by this proposal.

2019-12-04 15:28 UTC, ccvca commented
> Our policy is to keep GTests optional, which is broken by this proposal.
Sorry, the REQUIRED was only for debugging, should be still QUIET.

Branch updated

2020-05-04 07:48 UTC, ccvca commented
Any updates on this?

2020-05-04 08:07 UTC, alex-lotz commented
Was ist hier der Grund um den System Path auszuschließen? Die Variante die aktuell drin ist, ist doch bereits die maximal flexibelste und sollte in allen use-cases funktionieren.

2020-05-04 08:16 UTC, ccvca commented
Das Problem ist, dass cmake ein eigenes (veraltetes) Find-Skript mitliefert. Seit einiger Zeit liefert Googletest nun schon selbst eine CMake-Installation mit, die erweiterte Features (z.B. GMock-Support (Der im OPC UA Test schon genutzt wurde) ) mitliefert.
Das NO_CMAKE_SYSTEM_PACKAGE_REGISTRY verhindert, dass das eigene Find-Skript verwendet wird. Stattdessen wird normal nach GTest gesucht.

2020-05-04 14:34 UTC, alex-lotz commented
> Das Problem ist, dass cmake ein eigenes (veraltetes) Find-Skript mitliefert. Seit einiger Zeit liefert Googletest nun schon selbst eine CMake-Installation mit, die erweiterte Features (z.B. GMock-Support (Der im OPC UA Test schon genutzt wurde) ) mitliefert.
> Das NO_CMAKE_SYSTEM_PACKAGE_REGISTRY verhindert, dass das eigene Find-Skript verwendet wird. Stattdessen wird normal nach GTest gesucht.

Das erklärt NO_CMAKE_SYSTEM_PACKAGE_REGISTRY, aber warum dann NO_CMAKE_SYSTEM_PATH bei der Config file?

2020-05-04 14:52 UTC, ccvca commented
Weil ich das im 2. übersehen hatte zu Ändern. Die wirkung von beiden ist sehr ähnlich, und lößt das Problem erst mal.

2020-05-04 15:02 UTC, alex-lotz commented
> Weil ich das im 2. übersehen hatte zu Ändern. Die wirkung von beiden ist sehr ähnlich, und lößt das Problem erst mal.

Kannst du das Config File entsprechend einheitlich machen in einem weiteren commit, dann schaue ich mir die Sache genauer an?

2020-05-04 15:03 UTC, alex-lotz commented
PS: hab gerade gesehen dass du das schon gemacht hast :-)

2020-05-04 15:41 UTC, alex-lotz approved these changes

2020-05-04 15:41 UTC, merged